catsII/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve
      post :deny
    end
  end

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  root to: redirect('/cats')
end

catsII/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  user_name       :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :user_name, :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :password_digest, presence: { message: 'Password can\'t be blank' }
  before_validation :ensure_session_token


attr_reader :password


  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def password=(input_password)
    @password = input_password
    self.password_digest = BCrypt::Password.create(input_password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(user_name, password)
    user = User.find_by(user_name: user_name)
    return nil if user.nil?
    if user.is_password?(password)
        user
    else
      nil
    end
  end



end

catsII/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to cats_url
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :password)
  end
end

catsII/app/views/users/_form.html.erb
<% if type == :new %>
<% action_url = users_url%>
<% button_text = "Create User!"%>
<% else %>
<% action_url = session_url %>
<% button_text = "Log In User!"%>
<%# <% else %>
<%# action_url = user_url(template_user)%>
<%# button_text = "Update User!"%>
<% end  %>

<ul>
  <% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
      <li>
        <%= error %>
      </li>
    <% end %>
  <% end %>
</ul>

<form action="<%=action_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />

  <%# <% if type == :edit%>
  <!-- <input type="hidden" name="_method" value="patch"> -->
  <%# end %>

  <label for="user_name">
    Username:
    <input type="text" name="user[user_name]">
  </label>

  <label for="password">
    Password:
    <input type="password" name="user[password]">
  </label>

  <input type="submit" value="<%= button_text %>">
</form>

catsII/app/views/users/new.html.erb
<h1>Create new profile!</h1>

<%= render 'form', type: :new %>